const Flights = [
    {
        flightName : "CMR256",
        seatNumber : "12B",
        category : "B",
        departureAirport : "Yaounde",
        destination : "Tokyo",
        price : 800000,
        departureTime : "12am 25/03/2021",
        arrival : "6pm 25/03/2021",
    },
    {
        flightName : "CMR256",
        seatNumber : "31C",
        category : "A",
        price : 550000,
        departureAirport : "Douala",
        destination : "Dubai",
        departureTime : "12am 02/04/2021",
        arrival : "2pm 02/04/2021",
    },
    {
        flightName : "AirFr23",
        seatNumber : "18F",
        category : "B",
        price : 500000,
        departureAirport : "Yaounde",
        destination : "Brussels",
        departureTime : "12am 25/03/2021",
        arrival : "3pm 25/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    },
    {
        flightName : "PRT52",
        seatNumber : "25R",
        category : "A",
        departureAirport : "Douala",
        destination : "Lisbon",
        price : 600000,
        departureTime : "2pm 19/03/2021",
        arrival : "6pm 22/03/2021",
    },
    {
        flightName : "USA23",
        seatNumber : "99m",
        category : "B",
        departureAirport : "Douala",
        destination : "Chicago",
        price : 1200000,
        departureTime : "2pm 25/03/2021",
        arrival : "6pm 26/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    },
    {
        flightName : "CMR256",
        seatNumber : "12B",
        category : "B",
        departureAirport : "Yaounde",
        destination : "Tokyo",
        price : 800000,
        departureTime : "12am 25/03/2021",
        arrival : "6pm 25/03/2021",
    },
    {
        flightName : "CMR256",
        seatNumber : "31C",
        category : "A",
        price : 550000,
        departureAirport : "Douala",
        destination : "Dubai",
        departureTime : "12am 02/04/2021",
        arrival : "2pm 02/04/2021",
    },
    {
        flightName : "AirFr23",
        seatNumber : "18F",
        category : "B",
        price : 500000,
        departureAirport : "Yaounde",
        destination : "Brussels",
        departureTime : "12am 25/03/2021",
        arrival : "3pm 25/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    },
    {
        flightName : "PRT52",
        seatNumber : "25R",
        category : "A",
        departureAirport : "Douala",
        destination : "Lisbon",
        price : 600000,
        departureTime : "2pm 19/03/2021",
        arrival : "6pm 22/03/2021",
    },
    {
        flightName : "USA23",
        seatNumber : "99m",
        category : "B",
        departureAirport : "Douala",
        destination : "Chicago",
        price : 1200000,
        departureTime : "2pm 25/03/2021",
        arrival : "6pm 26/03/2021",
    },
    {
        flightName : "Eth505",
        seatNumber : "E12",
        category : "A",
        departureAirport : "Douala",
        destination : "Paris",
        price : 700000,
        departureTime : "2pm 20/03/2021",
        arrival : "6pm 20/03/2021",
    }
];

const m = [
    {
        firstName : "Hans",
        LastName : "Sebal",
        email : "hansSebal@yahoo.com",
        subject : "flight attendance",
        message : "mlsdjfmk mlkjdsfqlkj mlksjdljkjbn"
    },
    {
        firstName : "Hans",
        LastName : "Sebal",
        email : "hansSebal@yahoo.com",
        subject : "flight attendance",
        message : "mlsdjfmk mlkjdsfqlkj mlksjdljkjbn"
    },
    {
        firstName : "Hans",
        LastName : "Sebal",
        email : "hansSebal@yahoo.com",
        subject : "flight attendance",
        message : "mlsdjfmk mlkjdsfqlkj mlksjdljkjbn"
    }
];

const Users = [
    {
        id : 1,
        firstName : "Hans",
        LastName : "Dikaki",
        email : "hansD@yahoo.com",
        password : "yts.am"
    }
];

export {Flights,m,Users};